### ISSUE TITLE
Nota

### ISSUE THREAD

**Issue by fsantanna-uerj** [lrabbt/EDL#3]
Favor dividir 22.5 pontos entre vocês.                                            
A nota máxima é 8.

**Comment by fsantanna-uerj** [comment]
?

**Comment by lrabbt** [comment]
Professor, a divisão será por igual, desse modo:
* Breno Brandão - 7,5
* Bruno de Barros - 7,5
* Ingryd Moura - 7,5

**Comment by fsantanna-uerj** [comment]
ok
